version: 2

project_name: momd

builds:
  - binary: momd
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    dir: cmd/momd
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags "-static"
      -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

gomod:
  proxy: false

sboms:
  - artifacts: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

release:
  github:
    owner: mchmarny
    name: momd
  prerelease: auto

brews:
  - name: momd
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Rank Kubernetes pods/containers by CPU/memory usage (usage รท limit)."
    homepage: "https://github.com/mchmarny/momd"
    repository:
      owner: mchmarny
      name: homebrew-momd
      branch: main
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    install: |
      bin.install "momd"
    test: |
      system "#{bin}/momd --help"

archives:
  - id: momd
    formats:
      - tar.gz
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^lint:"
      - "^chore: readme"
      - "^chore: bump version"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Tasks"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
